package seeds

import (
	"log"

	"trackcard-server/models"

	"gorm.io/gorm"
)

// SeedCorePorts 初始化全球Top 20核心枢纽港口数据
func SeedCorePorts(db *gorm.DB) error {
	corePorts := []models.Port{
		// 亚太地区 (8个)
		{
			Code:              "CNSHA",
			Name:              "上海港",
			NameEn:            "Shanghai",
			Country:           "CN",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          31.3636,
			Longitude:         121.6042,
			Timezone:          "Asia/Shanghai",
			GeofenceKM:        20,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   3,
		},
		{
			Code:              "SGSIN",
			Name:              "新加坡港",
			NameEn:            "Singapore",
			Country:           "SG",
			Region:            "Southeast Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          1.2640,
			Longitude:         103.8400,
			Timezone:          "Asia/Singapore",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "CNNBG",
			Name:              "宁波港",
			NameEn:            "Ningbo",
			Country:           "CN",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          29.8972,
			Longitude:         121.8443,
			Timezone:          "Asia/Shanghai",
			GeofenceKM:        18,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   3,
		},
		{
			Code:              "CNSZX",
			Name:              "深圳港",
			NameEn:            "Shenzhen",
			Country:           "CN",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          22.5026,
			Longitude:         113.9069,
			Timezone:          "Asia/Shanghai",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "KRPUS",
			Name:              "釜山港",
			NameEn:            "Busan",
			Country:           "KR",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          35.1017,
			Longitude:         129.0402,
			Timezone:          "Asia/Seoul",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "HKHKG",
			Name:              "香港港",
			NameEn:            "Hong Kong",
			Country:           "HK",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          22.3458,
			Longitude:         114.1258,
			Timezone:          "Asia/Hong_Kong",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "CNQIN",
			Name:              "青岛港",
			NameEn:            "Qingdao",
			Country:           "CN",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          36.0911,
			Longitude:         120.3725,
			Timezone:          "Asia/Shanghai",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "MYPKG",
			Name:              "巴生港",
			NameEn:            "Port Klang",
			Country:           "MY",
			Region:            "Southeast Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          2.9999,
			Longitude:         101.3928,
			Timezone:          "Asia/Kuala_Lumpur",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},

		// 欧洲地区 (5个)
		{
			Code:              "NLRTM",
			Name:              "鹿特丹港",
			NameEn:            "Rotterdam",
			Country:           "NL",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              1,
			Latitude:          51.9565,
			Longitude:         4.1419,
			Timezone:          "Europe/Amsterdam",
			GeofenceKM:        20,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "BEANR",
			Name:              "安特卫普港",
			NameEn:            "Antwerp",
			Country:           "BE",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              1,
			Latitude:          51.2625,
			Longitude:         4.3435,
			Timezone:          "Europe/Brussels",
			GeofenceKM:        18,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "DEHAM",
			Name:              "汉堡港",
			NameEn:            "Hamburg",
			Country:           "DE",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              1,
			Latitude:          53.5352,
			Longitude:         9.9678,
			Timezone:          "Europe/Berlin",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "GBFXT",
			Name:              "费利克斯托港",
			NameEn:            "Felixstowe",
			Country:           "GB",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              1,
			Latitude:          51.9566,
			Longitude:         1.3117,
			Timezone:          "Europe/London",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 4,
			CongestionLevel:   3,
		},
		{
			Code:              "FRLEH",
			Name:              "勒阿弗尔港",
			NameEn:            "Le Havre",
			Country:           "FR",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              1,
			Latitude:          49.4820,
			Longitude:         0.1264,
			Timezone:          "Europe/Paris",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},

		// 北美地区 (5个)
		{
			Code:              "USLAX",
			Name:              "洛杉矶港",
			NameEn:            "Los Angeles",
			Country:           "US",
			Region:            "North America",
			Type:              "seaport",
			Tier:              1,
			Latitude:          33.7288,
			Longitude:         -118.262,
			Timezone:          "America/Los_Angeles",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   4,
		},
		{
			Code:              "USLGB",
			Name:              "长滩港",
			NameEn:            "Long Beach",
			Country:           "US",
			Region:            "North America",
			Type:              "seaport",
			Tier:              1,
			Latitude:          33.7542,
			Longitude:         -118.216,
			Timezone:          "America/Los_Angeles",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   4,
		},
		{
			Code:              "USNYC",
			Name:              "纽约港",
			NameEn:            "New York",
			Country:           "US",
			Region:            "North America",
			Type:              "seaport",
			Tier:              1,
			Latitude:          40.6661,
			Longitude:         -74.1557,
			Timezone:          "America/New_York",
			GeofenceKM:        18,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   3,
		},
		{
			Code:              "USSAV",
			Name:              "萨凡纳港",
			NameEn:            "Savannah",
			Country:           "US",
			Region:            "North America",
			Type:              "seaport",
			Tier:              1,
			Latitude:          32.1158,
			Longitude:         -81.1235,
			Timezone:          "America/New_York",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "CAVAN",
			Name:              "温哥华港",
			NameEn:            "Vancouver",
			Country:           "CA",
			Region:            "North America",
			Type:              "seaport",
			Tier:              1,
			Latitude:          49.2952,
			Longitude:         -123.076,
			Timezone:          "America/Vancouver",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},

		// 中东及其他 (2个)
		{
			Code:              "AEJEA",
			Name:              "杰贝阿里港",
			NameEn:            "Jebel Ali",
			Country:           "AE",
			Region:            "Middle East",
			Type:              "seaport",
			Tier:              1,
			Latitude:          25.0069,
			Longitude:         55.0597,
			Timezone:          "Asia/Dubai",
			GeofenceKM:        18,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "LKCMB",
			Name:              "科伦坡港",
			NameEn:            "Colombo",
			Country:           "LK",
			Region:            "South Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          6.9497,
			Longitude:         79.8457,
			Timezone:          "Asia/Colombo",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 3,
			CongestionLevel:   2,
		},

		// ========== 扩展港口 ==========

		// 亚太地区扩展 (10个)
		{
			Code:              "JPTYO",
			Name:              "东京港",
			NameEn:            "Tokyo",
			Country:           "JP",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          35.6528,
			Longitude:         139.7628,
			Timezone:          "Asia/Tokyo",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "JPYOK",
			Name:              "横滨港",
			NameEn:            "Yokohama",
			Country:           "JP",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          35.4537,
			Longitude:         139.6380,
			Timezone:          "Asia/Tokyo",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "TWKHH",
			Name:              "高雄港",
			NameEn:            "Kaohsiung",
			Country:           "TW",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          22.6100,
			Longitude:         120.2835,
			Timezone:          "Asia/Taipei",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "CNTAO",
			Name:              "天津港",
			NameEn:            "Tianjin",
			Country:           "CN",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          38.9800,
			Longitude:         117.7103,
			Timezone:          "Asia/Shanghai",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   3,
		},
		{
			Code:              "CNXMN",
			Name:              "厦门港",
			NameEn:            "Xiamen",
			Country:           "CN",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              2,
			Latitude:          24.4498,
			Longitude:         118.0819,
			Timezone:          "Asia/Shanghai",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "CNGZU",
			Name:              "广州港",
			NameEn:            "Guangzhou",
			Country:           "CN",
			Region:            "East Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          23.0778,
			Longitude:         113.3300,
			Timezone:          "Asia/Shanghai",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   3,
		},
		{
			Code:              "VNSGN",
			Name:              "胡志明港",
			NameEn:            "Ho Chi Minh",
			Country:           "VN",
			Region:            "Southeast Asia",
			Type:              "seaport",
			Tier:              2,
			Latitude:          10.7509,
			Longitude:         106.7453,
			Timezone:          "Asia/Ho_Chi_Minh",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 3,
			CongestionLevel:   3,
		},
		{
			Code:              "THLCH",
			Name:              "林查班港",
			NameEn:            "Laem Chabang",
			Country:           "TH",
			Region:            "Southeast Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          13.0778,
			Longitude:         100.8761,
			Timezone:          "Asia/Bangkok",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "IDJKT",
			Name:              "雅加达港",
			NameEn:            "Jakarta",
			Country:           "ID",
			Region:            "Southeast Asia",
			Type:              "seaport",
			Tier:              2,
			Latitude:          -6.0886,
			Longitude:         106.8800,
			Timezone:          "Asia/Jakarta",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 3,
			CongestionLevel:   3,
		},
		{
			Code:              "PHMNS",
			Name:              "马尼拉港",
			NameEn:            "Manila",
			Country:           "PH",
			Region:            "Southeast Asia",
			Type:              "seaport",
			Tier:              2,
			Latitude:          14.5900,
			Longitude:         120.9690,
			Timezone:          "Asia/Manila",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 3,
			CongestionLevel:   3,
		},

		// 南亚扩展 (3个)
		{
			Code:              "INNSA",
			Name:              "孟买港",
			NameEn:            "Mumbai (JNPT)",
			Country:           "IN",
			Region:            "South Asia",
			Type:              "seaport",
			Tier:              1,
			Latitude:          18.9540,
			Longitude:         72.9510,
			Timezone:          "Asia/Kolkata",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 3,
			CongestionLevel:   3,
		},
		{
			Code:              "INMAA",
			Name:              "金奈港",
			NameEn:            "Chennai",
			Country:           "IN",
			Region:            "South Asia",
			Type:              "seaport",
			Tier:              2,
			Latitude:          13.0915,
			Longitude:         80.2978,
			Timezone:          "Asia/Kolkata",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 3,
			CongestionLevel:   2,
		},
		{
			Code:              "PKKAR",
			Name:              "卡拉奇港",
			NameEn:            "Karachi",
			Country:           "PK",
			Region:            "South Asia",
			Type:              "seaport",
			Tier:              2,
			Latitude:          24.8300,
			Longitude:         67.0030,
			Timezone:          "Asia/Karachi",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 2,
			CongestionLevel:   3,
		},

		// 欧洲扩展 (6个)
		{
			Code:              "ESALG",
			Name:              "阿尔赫西拉斯港",
			NameEn:            "Algeciras",
			Country:           "ES",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              1,
			Latitude:          36.1300,
			Longitude:         -5.4500,
			Timezone:          "Europe/Madrid",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "ESVLC",
			Name:              "瓦伦西亚港",
			NameEn:            "Valencia",
			Country:           "ES",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              1,
			Latitude:          39.4453,
			Longitude:         -0.3180,
			Timezone:          "Europe/Madrid",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "ITGOA",
			Name:              "热那亚港",
			NameEn:            "Genoa",
			Country:           "IT",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              2,
			Latitude:          44.4106,
			Longitude:         8.9328,
			Timezone:          "Europe/Rome",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 3,
			CongestionLevel:   2,
		},
		{
			Code:              "GRPIR",
			Name:              "比雷埃夫斯港",
			NameEn:            "Piraeus",
			Country:           "GR",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              1,
			Latitude:          37.9475,
			Longitude:         23.6369,
			Timezone:          "Europe/Athens",
			GeofenceKM:        10,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "PLGDN",
			Name:              "格但斯克港",
			NameEn:            "Gdansk",
			Country:           "PL",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              2,
			Latitude:          54.3750,
			Longitude:         18.6500,
			Timezone:          "Europe/Warsaw",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "SEGOT",
			Name:              "哥德堡港",
			NameEn:            "Gothenburg",
			Country:           "SE",
			Region:            "Europe",
			Type:              "seaport",
			Tier:              2,
			Latitude:          57.7089,
			Longitude:         11.9746,
			Timezone:          "Europe/Stockholm",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 5,
			CongestionLevel:   1,
		},

		// 中东扩展 (4个)
		{
			Code:              "OMSLL",
			Name:              "塞拉莱港",
			NameEn:            "Salalah",
			Country:           "OM",
			Region:            "Middle East",
			Type:              "seaport",
			Tier:              2,
			Latitude:          16.9442,
			Longitude:         54.0042,
			Timezone:          "Asia/Muscat",
			GeofenceKM:        10,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   1,
		},
		{
			Code:              "SAJED",
			Name:              "吉达港",
			NameEn:            "Jeddah",
			Country:           "SA",
			Region:            "Middle East",
			Type:              "seaport",
			Tier:              1,
			Latitude:          21.4858,
			Longitude:         39.1925,
			Timezone:          "Asia/Riyadh",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "EGPSD",
			Name:              "塞德港",
			NameEn:            "Port Said",
			Country:           "EG",
			Region:            "Middle East",
			Type:              "seaport",
			Tier:              1,
			Latitude:          31.2653,
			Longitude:         32.3019,
			Timezone:          "Africa/Cairo",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 3,
			CongestionLevel:   2,
		},
		{
			Code:              "ILHFA",
			Name:              "海法港",
			NameEn:            "Haifa",
			Country:           "IL",
			Region:            "Middle East",
			Type:              "seaport",
			Tier:              2,
			Latitude:          32.8214,
			Longitude:         35.0053,
			Timezone:          "Asia/Jerusalem",
			GeofenceKM:        8,
			IsTransitHub:      false,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},

		// 南美地区 (5个)
		{
			Code:              "BRSSZ",
			Name:              "桑托斯港",
			NameEn:            "Santos",
			Country:           "BR",
			Region:            "South America",
			Type:              "seaport",
			Tier:              1,
			Latitude:          -23.9608,
			Longitude:         -46.3031,
			Timezone:          "America/Sao_Paulo",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 3,
			CongestionLevel:   3,
		},
		{
			Code:              "ARBUE",
			Name:              "布宜诺斯艾利斯港",
			NameEn:            "Buenos Aires",
			Country:           "AR",
			Region:            "South America",
			Type:              "seaport",
			Tier:              1,
			Latitude:          -34.5800,
			Longitude:         -58.3400,
			Timezone:          "America/Argentina/Buenos_Aires",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 3,
			CongestionLevel:   2,
		},
		{
			Code:              "CLVAP",
			Name:              "瓦尔帕莱索港",
			NameEn:            "Valparaiso",
			Country:           "CL",
			Region:            "South America",
			Type:              "seaport",
			Tier:              2,
			Latitude:          -33.0472,
			Longitude:         -71.6197,
			Timezone:          "America/Santiago",
			GeofenceKM:        8,
			IsTransitHub:      false,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "PECLL",
			Name:              "卡亚俄港",
			NameEn:            "Callao",
			Country:           "PE",
			Region:            "South America",
			Type:              "seaport",
			Tier:              2,
			Latitude:          -12.0464,
			Longitude:         -77.1428,
			Timezone:          "America/Lima",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 3,
			CongestionLevel:   2,
		},
		{
			Code:              "PAPTY",
			Name:              "巴拿马港",
			NameEn:            "Panama (Balboa)",
			Country:           "PA",
			Region:            "South America",
			Type:              "seaport",
			Tier:              1,
			Latitude:          9.0000,
			Longitude:         -79.5500,
			Timezone:          "America/Panama",
			GeofenceKM:        15,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},

		// 非洲地区 (4个)
		{
			Code:              "ZADUR",
			Name:              "德班港",
			NameEn:            "Durban",
			Country:           "ZA",
			Region:            "Africa",
			Type:              "seaport",
			Tier:              1,
			Latitude:          -29.8675,
			Longitude:         31.0292,
			Timezone:          "Africa/Johannesburg",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 3,
			CongestionLevel:   2,
		},
		{
			Code:              "MATNG",
			Name:              "丹吉尔港",
			NameEn:            "Tanger Med",
			Country:           "MA",
			Region:            "Africa",
			Type:              "seaport",
			Tier:              1,
			Latitude:          35.8797,
			Longitude:         -5.5056,
			Timezone:          "Africa/Casablanca",
			GeofenceKM:        12,
			IsTransitHub:      true,
			CustomsEfficiency: 4,
			CongestionLevel:   2,
		},
		{
			Code:              "KEMBA",
			Name:              "蒙巴萨港",
			NameEn:            "Mombasa",
			Country:           "KE",
			Region:            "Africa",
			Type:              "seaport",
			Tier:              2,
			Latitude:          -4.0435,
			Longitude:         39.6589,
			Timezone:          "Africa/Nairobi",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 2,
			CongestionLevel:   3,
		},
		{
			Code:              "NGLOS",
			Name:              "拉各斯港",
			NameEn:            "Lagos (Apapa)",
			Country:           "NG",
			Region:            "Africa",
			Type:              "seaport",
			Tier:              2,
			Latitude:          6.4403,
			Longitude:         3.3889,
			Timezone:          "Africa/Lagos",
			GeofenceKM:        10,
			IsTransitHub:      false,
			CustomsEfficiency: 2,
			CongestionLevel:   4,
		},

		// 大洋洲地区 (3个)
		{
			Code:              "AUSYD",
			Name:              "悉尼港",
			NameEn:            "Sydney",
			Country:           "AU",
			Region:            "Oceania",
			Type:              "seaport",
			Tier:              1,
			Latitude:          -33.8560,
			Longitude:         151.2106,
			Timezone:          "Australia/Sydney",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "AUMEL",
			Name:              "墨尔本港",
			NameEn:            "Melbourne",
			Country:           "AU",
			Region:            "Oceania",
			Type:              "seaport",
			Tier:              1,
			Latitude:          -37.8503,
			Longitude:         144.9276,
			Timezone:          "Australia/Melbourne",
			GeofenceKM:        12,
			IsTransitHub:      false,
			CustomsEfficiency: 5,
			CongestionLevel:   2,
		},
		{
			Code:              "NZAKL",
			Name:              "奥克兰港",
			NameEn:            "Auckland",
			Country:           "NZ",
			Region:            "Oceania",
			Type:              "seaport",
			Tier:              2,
			Latitude:          -36.8485,
			Longitude:         174.7633,
			Timezone:          "Pacific/Auckland",
			GeofenceKM:        8,
			IsTransitHub:      false,
			CustomsEfficiency: 5,
			CongestionLevel:   1,
		},
	}

	for _, port := range corePorts {
		// 使用FirstOrCreate避免重复创建
		var existing models.Port
		if err := db.Where("code = ?", port.Code).First(&existing).Error; err != nil {
			// 不存在则创建
			if err := db.Create(&port).Error; err != nil {
				log.Printf("Failed to seed port %s: %v", port.Code, err)
			} else {
				log.Printf("Seeded port: %s (%s)", port.Code, port.Name)
			}
		}
	}

	log.Printf("Core ports seeding completed. Total: %d ports", len(corePorts))
	return nil
}
